{"name": "Проверка возвращения ошибки при создании курьера с уже существующим логином", "status": "passed", "start": 1728215416616, "stop": 1728215416672, "uuid": "d151d135-f6f5-4a74-bb72-8fc32b131a07", "historyId": "eccfa29233b58a7619bf2ba51ee2654a", "testCaseId": "eccfa29233b58a7619bf2ba51ee2654a", "fullName": "tests.test_create_new_courier.TestCreateNewCourier#test_create_two_couriers_with_same_login_second_courier_impossible_to_create", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_new_courier"}, {"name": "subSuite", "value": "TestCreateNewCourier"}, {"name": "host", "value": "DESKTOP-ABCQNV2"}, {"name": "thread", "value": "10120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_new_courier"}]}