{"name": "Проверка возврата ошибки при авторизации под несуществующим пользователем", "status": "passed", "start": 1728215415933, "stop": 1728215415991, "uuid": "ded84c49-641b-43ad-a365-c3fb22c79e13", "historyId": "1b7e4b296a005761317f4dda252eac1a", "testCaseId": "1b7e4b296a005761317f4dda252eac1a", "fullName": "tests.test_courier_log_in.TestCourierLogIn#test_error_log_in_with_non_existing_user_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_log_in"}, {"name": "subSuite", "value": "TestCourierLogIn"}, {"name": "host", "value": "DESKTOP-ABCQNV2"}, {"name": "thread", "value": "10120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_log_in"}]}